exp10/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name  = "main"
urlpatterns = [
    path('', views.index, name="index"),
    path("create", views.AuthorCreateView.as_view(), name="create"),
    path("<pk>/update", views.AuthorUpdateView.as_view(), name="update"),
    path("<pk>/delete", views.AuthorDeleteView.as_view(), name="delete"),
]

main/models.py
from django.db import models

# Create your models here.
class Ipl(models.Model):
    team_name = models.CharField(max_length=200, null=True, blank= True)
    wins = models.IntegerField(max_length=200, null=True, blank= True)
    losses = models.IntegerField(max_length=200, null=True, blank= True)
    played = models.IntegerField(max_length=200, null=True, blank= True)


    class Meta:
        db_table = 'IPL'

main/views.py
from django.shortcuts import render
from .models import Ipl
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView,DeleteView
from django.urls import reverse

# Create your views here.
def index(request):
    teams = Ipl.objects.filter().all()
    context = {'teams' : teams}
    return render(request,"index.html", context)



class AuthorCreateView(CreateView):
    model = Ipl
    template_name = "create.html"
    fields = ["team_name","wins", "losses"]
    success_url =  "/"
    # def get_success_url(self):
    #     return reverse('index')


class AuthorUpdateView(UpdateView):
    model = Ipl
    template_name = "create.html"
    template_name_suffix = "_update_form"
    fields = ["team_name","wins", "losses"]
    success_url =  "/"
    

class AuthorDeleteView(DeleteView):
    model = Ipl
    template_name = "delete.html"
    success_url =  "/"

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>
        
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'main:create' %} ">Create</a>
   {% for team in teams %}
        <h1>
            {{team.team_name}}
            <a href="{% url 'main:update' pk=team.id %} ">Update</a>
            <a href="{% url 'main:delete' pk=team.id %} ">Delete</a>
        </h1>
   {% endfor %}
   
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width= , initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</body>
</html>